### ISSUE TITLE
Error when running LIVO/VIO mode, but LIO mode works fine.

### ISSUE THREAD

**Issue by kdgreater1** [RoboSense-Robotics/robosense_ac_slam#4]
Thank you for open-sourcing the code. I'm really looking forward to the official release of AC1. While running the official data (shuichi), I encountered some issues: the program crashes when using LIVO/VIO mode, but works fine in LIO mode. I'm running it on Ubuntu 20.04 with ROS1.

Here's the error log when running LIVO:

camera width: 960 height: 540
FastLivoSlam: init succeed!
topic: lidar: /rs_lidar/points imu: /rs_imu camera: /rs_camera/rgb compressed_img_topic: 
FastLivoSlam Core loop start. 
[ INPUT ] lidar size: 27648 first pt t:1741936548.500216 last pt t:1741936548.591581 header: 1741936548.591581
[ INPUT ] bad_dis_cnt:0 zero_dis_cnt:0 nan_cnt:12960
[ INPUT ] preprocess cloud done, header_ts: 1741936548.591581 cloud_ts: 1741936548.591581 size: 14688 cost(ms): 1.018848.
[ INPUT ] lidar size: 27648 first pt t:1741936548.600216 last pt t:1741936548.691586 header: 1741936548.691586
[ INPUT ] bad_dis_cnt:0 zero_dis_cnt:0 nan_cnt:12988
[ INPUT ] preprocess cloud done, header_ts: 1741936548.691586 cloud_ts: 1741936548.691586 size: 14660 cost(ms): 1.973534.
[ INPUT ] lidar size: 27648 first pt t:1741936548.700216 last pt t:1741936548.791583 header: 1741936548.791583
[ INPUT ] bad_dis_cnt:0 zero_dis_cnt:0 nan_cnt:12991
[ INPUT ] preprocess cloud done, header_ts: 1741936548.791583 cloud_ts: 1741936548.791583 size: 14657 cost(ms): 1.445638.
[ INPUT ] lidar size: 27648 first pt t:1741936548.800217 last pt t:1741936548.891583 header: 1741936548.891583
[ INPUT ] bad_dis_cnt:0 zero_dis_cnt:0 nan_cnt:13253
[ INPUT ] preprocess cloud done, header_ts: 1741936548.891583 cloud_ts: 1741936548.891583 size: 14395 cost(ms): 1.465291.
[ Debug time ] last_timestamp_lidar: 0.000, msg_header_time: 1741936548.421, last_lidar+0.1: 0.100
[ ProcessMsgBufferLoop ] get img at time: 1741936548.421. img-lidar: -1741936548.321. img-last_img: 1741936548.421. imu: 0
[ Debug time ] last_timestamp_lidar: 0.000, msg_header_time: 1741936548.487, last_lidar+0.1: 0.100
[ ProcessMsgBufferLoop ] get img at time: 1741936548.487. img-lidar: -1741936548.387. img-last_img: 0.067. imu: 0
[laserMapping-2] process has died [pid 35455, exit code -11, cmd /home/pc1/zhitai/robosense_slam_ws/devel/lib/slam/slam_node __name:=laserMapping __log:=/home/pc1/.ros/log/20b181a8-15f2-11f0-96b2-d53430ee1ccf/laserMapping-2.log].

It seems there might be an issue with obtaining the lidar and imu timestamps? How can I solve this problem? Thank you!

**Comment by lwbdegit** [comment]
Thank you for test and we're glad to provide assistant to solver the problem. 

It's normal in my test, and the result shows as the pic below. 
![Image](https://github.com/user-attachments/assets/113e5df3-6976-42c8-8d66-f3c66df1b937)
Seems an crash occurs at the Red Arrow position in your enviroment. 

Please:
1. check any different about sensor extrinsic and intrinsic (Red Box in pic) which locate in 'calibration.yaml'
2. set 'save_log' to true in 'RS_META.yaml', launch again, and get some logs in 'Log' folder .
Show 'drop_msg.txt' and 'sensor_buffer.txt' will be helpful to locate the problem.
3. check if bag play is lagging. Try to rosbag play at lower speed (like with '-r 0.5') to see if problem could be solved

My configs are for your reference.

- calibration.yaml
```
DEVICE_ID: 1111BE070010
Body:
  base_link: base_link
  frame: sensor
  extrinsic:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    quaternion:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
Sensor:
  Lidar:
    base_link: sensor
    frame: lidar
    extrinsic:
      translation:
        x: 0.0
        y: 0.030219
        z: -0.02354
      quaternion:
        x: 0.0
        y: -0.0
        z: 0.0
        w: 1.0
  Camera:
    base_link: sensor
    frame: camera
    extrinsic:
      translation:
        x: -0.01
        y: 0.02
        z: -0.04708
      quaternion:
        x: 0.5000000001025516
        y: -0.49999999979489657
        z: 0.5000000001025517
        w: -0.5
    intrinsic:
      model: Pinhole
      int_matrix:
      - 792.4640737604
      - 0
      - 965.645594
      - 0
      - 791.1053752151
      - 547.250649
      - 0
      - 0
      - 1
      dist_coeff:
      - -0.0352108256
      - 0.147926732
      - 1.2937e-05
      - 0.0001654014
      - 0.014088817
      - 0.290436
      - 0.095993
      - 0.061735
      image_size:
      - 1920
      - 1080
  IMU:
    base_link: sensor
    frame: imu
    extrinsic:
      translation:
        x: 0.0
        y: 0.0
        z: 0.0
      quaternion:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
ADDTION_INFO:
  cam_model: Pinhole
  cam_width: 1920
  cam_height: 1080
  cam_fx: 792.4640737604
  cam_fy: 791.1053752151
  cam_cx: 965.645594
  cam_cy: 547.250649
  cam_d0: -0.0352108256
  cam_d1: 0.147926732
  cam_d2: 1.2937e-05
  cam_d3: 0.0001654014
  cam_d4: 0.014088817
  cam_d5: 0.290436
  cam_d6: 0.095993
  cam_d7: 0.061735
  Rcl:
  - 2.0510342851533115e-10
  - -1.0
  - 4.102068570306623e-10
  - 2.05103428599466e-10
  - -4.102068569885949e-10
  - -1.0
  - 1.0
  - 2.05103428599466e-10
  - 2.0510342851533115e-10
  Pcl:
  - 0.030219000009656268
  - -0.023539999987603956
  - -1.3698858015963676e-12
  extrinsic_T:
  - 0
  - 0.030219
  - -0.02354
  extrinsic_R:
  - 1
  - -0.0
  - -0.0
  - 0.0
  - 1
  - -0.0
  - 0.0
  - 0.0
  - 1

```

- RS_META.yaml
```
# 传感器内外参从calibration.yaml读取

# 传感器消息话题
topic:
    lid_topic:  "/rslidar_points_meta"
    imu_topic:  "/rslidar_imuData_meta"
    img_topic: /image_rgb
    # compressed_img_topic: /rs_camera/rgb # 临时手动选择 压缩话题是否同名等待商议

# 传感器开关
img_enable : 1 # 0代表不使用图像 LIO模式
lidar_enable : 1 # 0代表不使用激光雷达 VIO模式

# 传感器优化权重
img_point_cov : 0.1 # 可以调整. 已按照超传标准分辨率设置，内部自动除以缩放系数img_scaling_ratio平方
laser_point_cov : 0.0005 # 可以调整

# IMU权重 (注意：室内外参数差异较大，室内参考rs_data_config/RS_META_indoor.yaml， 室外参考RS_META_outdoor.yaml)
use_cfg_cov: false # IMU协方差是否使用配置中的， false则自动计算
# cov_acc: 0.1
# cov_gyr: 0.1
# cov_bias_acc: 0.0001
# cov_bias_gyr: 0.0001
# init_cov_rot: 1
# init_cov_pos: 1
# init_cov_vel: 1
# init_cov_bias_gyr: 1e-4
# init_cov_bias_acc: 1e-3

# LIO
point_filter_num : 1 # lidar点云采样频率 可以调整, 如果想滤除拖点必须设为1
max_iteration : 5 # 最大优化次数 可以调整
filter_size_surf : 0.3 # source点栅格尺寸 可以调整 室内减小 (注意：室内外参数差异较大)
filter_size_map : 0.3 # ikdtree地图栅格尺寸 可以调整 室内减小
cube_side_length : 20 # 点云地图格子尺寸（m）
lidar_max_range: 30 # lidar测距范围， 过大导致地图点过多降低性能

# VIO
grid_size : 40 # 图像地图格子尺寸（像素） 控制图像点密度，越大点越少. 已按照超传标准分辨率设置，内部自动乘以缩放系数img_scaling_ratio
patch_size : 20 #24 # 图像patch尺寸（像素）可以调整 越小越快. 已按照超传标准分辨率设置，内部自动乘以缩放系数img_scaling_ratio

# RS新功能
rs:
    delay_t: 0.5 # 算法滞后时间，避免旧数据插入buffer (s)

    # LIO
    boundary_point_remove: true # 滤除拖点
    downsample_source_cloud: true # 是否给source降采样
    p2plane_thresh:  0.5 # 有效匹配点对距离(m)

    # VIO
    vis_down_leaf: 0.5 # 点云投影到地图前降采样 (m)
    VIO_wait_time: 0 #2. # VIO初始化等待时间
    use_map_proj: true # 使用点云地图投影， 扩大img特征点范围。 仅用于LIDAR FOV小于CAM

    light_min_thresh:  2 #3 #5.0 # 光度标准差阈值， 光度变化小的patch被滤除
    sub_sparse_map_error_thresh: 5  # 平均光度误差，用于可视化
    depth_continuous_thresh: 1.5 # (m)
    global_map_voxel_size: 0.5 # 0.5 (m)
    max_layer: 3
    max_obs_num: 20

    enable_normal_filter: true # 过滤提供给提供VIO的lidar噪点
    norm_thresh: 80 #60  # 平面法线与光心射线夹角阈值，过大的平面被滤除。 (度)
    weight: 1 # 0.5 噪点降权
    # 将lidar地图投影到图像，召回特征点
    z_thresh: 20 # 高于阈值被过滤
    y_thresh: 20
    x_thresh: 20
    weight2_ref_depth: -10. #10. # -10 基于不确定度的权重,期望全场景都具有泛化性; 0 固定权重１; 任意正数x，按相机观测距离线性降权, xm处权重为1。 对近处点降权，适用斜视场景，如草地。对于深度差过大的场景会降低精度。(米)

    # 过滤视觉特征
    img_filter:
        cam_keep_period: 3 # 每3留1, -1代表用时间过滤
        delta_time: 0 # 图像时间戳修正 (s)
        img_scaling_ratio: 0.5 # 图像缩放系数，用于降低分辨率 推荐0.3~0.7
        map_value_thresh: 10 # 角点响应值最小值，低于过滤
        outlier_threshold : 1500 # 78 100 156 # 视觉patch残差阈值，大于则过滤 可以调整 越小越快
        ncc_en: false
        ncc_thre: 0
        remove_down_pixel: 2500 # img行裁剪，正数代表大于该行被滤除，负数代表小于绝对值的行被滤除
        uniform_feature: 0 # 非0代表开启，数值*patch_size_half 为非极大值抑制的半径
        exp_num_per_grid: 3 # 非极大值抑制，每个格子保留几个特征点
        patch_num_max: 200 # 选取响应值最大的前若干点
        source_base_weight: -1 # patch基础权重。>0代表按到图像中心的距离降权(因为图像畸变，远处误差大)
        target_base_weight: -1
    
    # 退化检测
    degeneration:
        vis_degenerate_thresh: 0.1 # 0.35 # 视觉退化阈值，低于此值退化成LIO (注意：室内外参数差异较大)
        detect_lidar_degenetate: true # 开启点云退化检测
        lidar_degenerate_thresh: 0.05 # 0.15 # 点云退化阈值
        reset_state_when_degenerate: true # 点云退化时重置状态
    
    # debug
    rs_debug: false
    print_log: false
    save_log: true

    # 可视化
    vio_pub:
        pub_noise_cloud: false # 发布噪声点云
        pub_all_cloud: false # 发布所有点云
        depth_color_range: 5 # L系下x 5m内颜色渐变
    visualize:
        trans_imu_to_lidar: true # 是否把IMU数据转到Lidar系
        pub_dense_map: true # 地图是否稠密（非降采样）
        show_lidar_map: true # 发布强度地图
        show_rgb_map: true # 发布rgb地图

pcd_save:
    pcd_save_en: false
    ply_save_en: false
    save_frame_mode: "" # "single_pcd" "sinlge_ply" "whole_pcd" or "whole_ply"
    voxel_size: 0.03 # >0额外保存降栅格采样点云。(米)

    # 读取pcd并降采样
    pcd_in: "xxx.pcd"
    pcd_out: "xxx.pcd" # 支持.pcd .ply

preprocess:
    lidar_type: 2 # 1:Livox LiDAR  2:RS Meta(AC)  3:OUST64  4:XT32  5:Mid360
    scan_line: 4 # 16  64  32
    blind: 0.5 # blind x m disable
    blind_max: 100.0

imu:
    vrw: 1e-1
    arw: 1e-2
    sigma_ba: 1e-3
    sigma_bg: 1e-4 
    cov_acc: 1e-4 #2.5e-1
    cov_gyr: 1e-6 #9e-2

local_map:  
  map_sliding_en: false
  half_map_length: 50.
  sliding_thresh: 8.
```

- sensor_buffer.txt
```
cam 1741936548.420511 img_cnt:1 3 1 img-lidar -1741936548.320511 img-last img: 1741936548.420511 imu: 0
cam 1741936548.487177 img_cnt:2 3 1 img-lidar -1741936548.387177 img-last img: 0.066666 imu: 0
cam 1741936548.520511 img_cnt:3 3 1 img-lidar -1741936548.420511 img-last img: 0.033334 imu: 0
 first imu 1741936548.522856
 imu 1741936548.527807 cnt: 1
 imu 1741936548.532743 cnt: 2
 imu 1741936548.537689 cnt: 3
 imu 1741936548.542631 cnt: 4
 imu 1741936548.547575 cnt: 5
 imu 1741936548.552518 cnt: 6
cam 1741936548.553845 img_cnt:4 3 1 img-lidar -1741936548.453845 img-last img: 0.033334 imu: 7
 imu 1741936548.557466 cnt: 7
 imu 1741936548.562412 cnt: 8
 imu 1741936548.567353 cnt: 9
 imu 1741936548.572296 cnt: 10
 imu 1741936548.577241 cnt: 11
 imu 1741936548.582185 cnt: 12
 imu 1741936548.587129 cnt: 13
cam 1741936548.587177 img_cnt:5 3 1 img-lidar -1741936548.487177 img-last img: 0.033332 imu: 14
lid 1741936548.591581
 imu 1741936548.597018 cnt: 14
 imu 1741936548.601966 cnt: 15
 imu 1741936548.606909 cnt: 16
 imu 1741936548.611851 cnt: 17
 imu 1741936548.616795 cnt: 18
cam 1741936548.620509 img_cnt:6 3 1 img-lidar 0.071072 img-last img: 0.033332 imu: 19
 imu 1741936548.621740 cnt: 19
 imu 1741936548.626687 cnt: 20
 imu 1741936548.631627 cnt: 21
 imu 1741936548.636573 cnt: 22
 imu 1741936548.641522 cnt: 23
 imu 1741936548.646461 cnt: 24
cam 1741936548.653844 img_cnt:7 3 1 img-lidar 0.037737 img-last img: 0.033335 imu: 11
 imu 1741936548.656349 cnt: 25
 imu 1741936548.661297 cnt: 26
 imu 1741936548.666255 cnt: 27
 imu 1741936548.671183 cnt: 28
 imu 1741936548.676126 cnt: 29
 imu 1741936548.681071 cnt: 30
 imu 1741936548.686014 cnt: 31
 imu 1741936548.690960 cnt: 32
lid 1741936548.691586
 imu 1741936548.695903 cnt: 33
 imu 1741936548.700847 cnt: 34
 imu 1741936548.705793 cnt: 35
 imu 1741936548.710736 cnt: 36
 imu 1741936548.715680 cnt: 37
cam 1741936548.720512 img_cnt:8 3 1 img-lidar 0.071074 img-last img: 0.066668 imu: 13
 imu 1741936548.720624 cnt: 38
 imu 1741936548.725571 cnt: 39
 imu 1741936548.730514 cnt: 40
 imu 1741936548.735457 cnt: 41
 imu 1741936548.740402 cnt: 42
 imu 1741936548.745346 cnt: 43
cam 1741936548.753843 img_cnt:9 3 1 img-lidar 0.037743 img-last img: 0.033331 imu: 19
```

- drop_msg.txt
```
empty
```
