### ISSUE TITLE
Does this repo support Airy?

### ISSUE THREAD

**Issue by alanxuefei** [RoboSense-Robotics/robosense_ac_slam#7]
It seems that the configuration for Airy is currently empty. May I check if this repository officially supports the Airy sensor?

Analysis:
1, Empty configs of Airy in RS_LOAM.yaml
https://github.com/RoboSense-Robotics/robosense_ac_slam/blob/main/config/RS_LOAM.yaml#L30

```
###E1
###Airy
###EM4
```
2, Based on the preprocess.cpp file, it appears that only the following sensor types are supported:
```
lidar_type: 2 # 1:Livox LiDAR  2:RS Meta(AC)  3:OUST64  4:XT32  5:Mid360
```

**Comment by alanxuefei** [comment]
Thanks for promote reply.

I’m trying to bring up the Airy sensor along with its internal IMU.

Although the LiDAR map is now being published, the camera_init frame drifts away from the aft_mapped frame.
Could this be caused by the IMU's accuracy?

The IMU data when the Airy is stationary is shown below:

```
angular_velocity:
  x: -0.011185277253389359
  y: 0.007456851191818714
  z: 0.0023968450259417295
angular_velocity_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: -0.0059814453125
  y: -0.0093994140625
  z: -0.996826171875
linear_acceleration_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```

@lwbdegit  Would you be able to recommend a ready-to-use localization kit for an outdoor SLAM scenario?
Our project aims to find a localization kit, rather than focusing solely on bringing up the Airy sensor.
